name: Failure

on:
  push:
    branches:
      - main

jobs:
  all-ok:
    runs-on: ubuntu-latest
    steps:
      - name: All ok
        run: echo "OK"
  epic-fail:
    runs-on: ubuntu-latest
    steps:
      - name: Epic Fail
        run: asdfasdf
