name: Manually triggered workflow

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: "Version number in x.x.x format\n1. si\n2. no"
        required: true
      version_code:
        description: "Integer number to use in project files"
        required: true

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Modify
        run: |
          echo 'hola' >> random.txt

      # Create commit and tag in release branch
      - name: Create commit and tag in release branch
        run: |
          echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          git add .
          git commit -m "Create release ${{ github.event.inputs.version_name }}"
          echo "commit_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          git tag -a ${{ github.event.inputs.version_name }} -m "version ${{ github.event.inputs.version_name }}"
          git push --follow-tags

      # Checkout to main branch, cherry-pick the tag commit and push it to main
      - name: Cherry-pick commit into main
        run: |
          git fetch
          git checkout main
          git cherry-pick ${{ env.commit_sha }}
          git push origin main
