name: Android publish

on:
  workflow_dispatch:
    inputs:
      publish_all_dependencies:
        description: "Publish all Android SDK dependencies"
        required: true
        default: "no"
      publish_amazon_iap:
        description: "Publish Amazon IAP SDK"
        required: true
        default: "no"
      publish_android_jsc:
        description: "Publish Android JSC SDK"
        required: true
        default: "no"
      publish_react_native_code_push:
        description: "Publish RN Code Push Android SDK"
        required: true
        default: "no"
      publish_react_native_hermes:
        description: "Publish Hermes Android SDK"
        required: true
        default: "no"
      publish_react_native_iap:
        description: "Publish RN IAP Android SDK"
        required: true
        default: "no"
      publish_react_native_localize:
        description: "Publish RN Localize Android SDK"
        required: true
        default: "no"
      publish_react_native_picker:
        description: "Publish RN Picker Android SDK"
        required: true
        default: "no"
      publish_react_native_sdk:
        description: "Publish React Native Android SDK"
        required: true
        default: "no"
      publish_react_native_webview:
        description: "Publish RN WebView Android SDK"
        required: true
        default: "no"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: publish_all_dependencies
            command: publishGiSdkDependenciesToDiscoveryNexus
          - name: publish_amazon_iap
            command: ":gi-amazon-iap:publishAllPublicationsToDiscoveryNexusRepository"
          - name: publish_android_jsc
            command: ":gi-android-jsc:publishAarPublicationToDiscoveryNexus"
          - name: publish_react_native_code_push
            command: ":gi-react-native-code-push:publishAarPublicationToDiscoveryNexus"
          - name: publish_react_native_hermes
            command: ":gi-hermes-release:publishAarPublicationToDiscoveryNexus"
          - name: publish_react_native_iap
            command: ":gi-react-native-iap:publishAllPublicationsToDiscoveryNexusRepository"
          - name: publish_react_native_localize
            command: ":gi-react-native-localize:publishAarPublicationToDiscoveryNexus"
          - name: publish_react_native_picker
            command: ":gi-react-native-picker:publishAarPublicationToDiscoveryNexus"
          - name: publish_react_native_sdk
            command: ":gi-react-native:publishAarPublicationToDiscoveryNexus"
          - name: publish_react_native_webview
            command: ":gi-react-native-webview:publishAarPublicationToDiscoveryNexus"
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "${{matrix.name}}"
          echo "${{ github.event.inputs.publish_all_dependencies}}"
