name: Pager Duty test

on:
  push:
    branches:
      - pager

jobs:
  pager:
    runs-on: ubuntu-latest
    steps:
      - name: Error
        run: |
          echo "Running an inexistent command"
          asdfasdf
      - name: Send PagerDuty alert on failure
        if: ${{ failure() }}
        uses: Entle/action-pagerduty-alert@0.1.0
        with:
          pagerduty-integration-key: '${{ secrets.PAGERDUTY_INTEGRATION_KEY }}'
          pagerduty-dedup-key: github_workflow_failed