name: pr-info

on:
  pull_request:
    branches:
      - main

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: action
        id: pr-info
        uses: Brymastr/pr-info-action@v1

      - name: Print
        run: |
          echo "${{ steps.pr-info.outputs.body }}"

      - name: Extract
        run: |
          substring=${${{ steps.pr-info.outputs.body }}#*Automation test config}
          buildConfig="{"$(echo $substring | cut -d "{" -f2 | cut -d "}" -f1)"}"
          echo $buildConfig
