name: pr-info

on:
  pull_request:
    branches:
      - main

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: action
        id: pr-info
        uses: Brymastr/pr-info-action@v1

      - name: Print
        run: |
          echo "${{ steps.pr-info.outputs.body }}"

      - name: Extract
        run: |
          echo "Running extract step"
          body=$(echo "${{ steps.pr-info.outputs.body }}" | tr -d '\n')
          substring=${body#*Automation test config}
          buildConfig="{"$(echo $substring | cut -d "{" -f2 | cut -d "}" -f1)"}"
          echo $buildConfig
          appBranch=$(echo $buildConfig | jq -r '.appBranch')
          echo $appBranch
