name: Android publish select

on:
  workflow_dispatch:
    inputs:
      action:
        description: |
          Use one of the following:
          publish_all_dependencies
          publish_amazon_iap
          publish_android_jsc
          publish_react_native_code_push
          publish_react_native_hermes
          publish_react_native_iap
          publish_react_native_localize
          publish_react_native_picker
          publish_react_native_sdk
          publish_react_native_webview
        required: true

env:
  publish_all_dependencies: "publishGiSdkDependenciesToDiscoveryNexus"
  publish_amazon_iap: ":gi-amazon-iap:publishAllPublicationsToDiscoveryNexusRepository"
  publish_android_jsc: ":gi-android-jsc:publishAarPublicationToDiscoveryNexus"
  publish_react_native_code_push: ":gi-react-native-code-push:publishAarPublicationToDiscoveryNexus"
  publish_react_native_hermes: ":gi-hermes-release:publishAarPublicationToDiscoveryNexus"
  publish_react_native_iap: ":gi-react-native-iap:publishAllPublicationsToDiscoveryNexusRepository"
  publish_react_native_localize: ":gi-react-native-localize:publishAarPublicationToDiscoveryNexus"
  publish_react_native_picker: ":gi-react-native-picker:publishAarPublicationToDiscoveryNexus"
  publish_react_native_sdk: ":gi-react-native:publishAarPublicationToDiscoveryNexus"
  publish_react_native_webview: ":gi-react-native-webview:publishAarPublicationToDiscoveryNexus"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          echo ${{ env[github.event.inputs.action] }}
