name: Result Success or Failure

on:
  push:
    branches:
      - test-result-success-failure

jobs:
  ok:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hola"
  not-ok:
    runs-on: ubuntu-latest
    steps:
      - run: |
          asdfasdf
  finally:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - ok
      - not-ok
    steps:
      - name: Validation
        id: validation
        run: |
          if [["${{needs.ok.result}}" = "failure"]]; then
            echo "::set-output name=result::build_failure"
          elif [["${{needs.not-ok.result}}" = "failure"]]; then
            echo "::set-output name=result::test_failure"
          else
            echo "::set-output name=result::success"
          fi

      - name: Print
        run: echo ${{steps.validation.outputs.result}}

