name: Result Success or Failure

on:
  push:
    branches:
      - test-result-success-failure

jobs:
  ok:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hola"
  not-ok:
    runs-on: ubuntu-latest
    steps:
      - run: |
          asdfasdf
  finally:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - ok
      - not-ok
    steps:
      - name: Dump ok context
        env:
          JOB_CONTEXT: ${{ toJSON(needs.ok) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump not-ok context
        env:
          STEPS_CONTEXT: ${{ toJSON(needs.not-ok) }}
        run: echo "$STEPS_CONTEXT"
